export const dummyApi=[
  {
    id:"1",
    number:"1",
    jobDetail:"Base Operation",
    requestId:"MRF22053112806",
    requestDate:"2023-02-03 14:58",
    requestor:"Alexander Ifeanyi",
    description:"SWIRE ENERGY SERVICES MINI CONTAINER RENTAL FOR 20 DAYS",
    department:"Cementing",
    amount:"165,000.00",
    hodApproval:"Approved",
    hodName:"TIMOTHY FAGBEMI",
    hodApprovalDate:"02/03/2023 16:06",
    storeAvailability:"Inventory verified",
    storeKeeper:"CHRISTIAN OKONKWO",
    storeVerificationDate: "2023-02-03 13:2",
    procurementUpdate:"Pending",
    hodPricingApproval:"Awaiting Approval",
    gmoApproval:"Not Required",
    buHeadApproval:"Approved by PATRICK AKPOJOTOR on 2023-02-03 16:09",
    directorApproval:"Not Required",
    paymentStatus:"Budget 06 Feb to 13 Feb",
    status:"pending"
  },
  {
    id:"2",
    number:"2",
    jobDetail:"Base Operation",
    requestId:"MRF22057112806",
    requestDate:"2023-02-03 14:58",
    requestor:"Alexander Ifeanyi",
    description:"SEAHAWK SPARES",
    department:"Cementing",
    amount:"165,000.00",
    hodApproval:"Awaiting Approval",
    hodName:"",
    hodApprovalDate:"",
    storeAvailability:"Awaiting Verification",
    storeKeeper:"",
    storeVerificationDate: "",
    procurementUpdate:"Pending",
    hodPricingApproval:"Awaiting Approval",
    gmoApproval:"Not Required",
    buHeadApproval:"Awaiting Approval",
    directorApproval:"Not Required",
    paymentStatus:"Pending",
    status:"pending"
  },
  {
    id:"3",
    number:"3",
    jobDetail:"Base Operation",
    requestId:"MRF22053112806",
    requestDate:"2023-02-03 14:58",
    requestor:"Alexander Ifeanyi",
    description:"SWIRE ENERGY SERVICES MINI CONTAINER RENTAL FOR 20 DAYS",
    department:"Cementing",
    amount:"165,000.00",
    hodApproval:"Approved",
    hodName:"TIMOTHY FAGBEMI",
    hodApprovalDate:"02/03/2023 16:06",
    storeAvailability:"Inventory verified",
    storeKeeper:"CHRISTIAN OKONKWO",
    storeVerificationDate: "2023-02-03 13:2",
    procurementUpdate:"Pending",
    hodPricingApproval:"Awaiting Approval",
    gmoApproval:"Not Required",
    buHeadApproval:"Approved by PATRICK AKPOJOTOR on 2023-02-03 16:09",
    directorApproval:"Not Required",
    paymentStatus:"Budget 06 Feb to 13 Feb",
    status:"pending"
  },
]
